RAID = [
    "ᴍᴀDᴀℛCHᴏD T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 GHUTKᴀ KHᴀᴀK𝑬 THᴏᴏK DUɴGᴀ 🤣🤣",
    "T𝑬ℛ𝑬 B𝑬H𝑬ɴ K CHUT ᴍ𝑬 CHᴀKU DᴀᴀL Kᴀℛ CHUT Kᴀ KHᴏᴏɴ Kᴀℛ DUGᴀ",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ ɴHI HᴀI KYᴀ? 9 ᴍᴀHIɴ𝑬 ℛUK 🇸 ᴀGI VᴀH𝑬𝑬ɴ D𝑬Tᴀ HU 🤣🤣🤩",
    "T𝑬ℛI ᴍᴀᴀ K BHᴏ🇸 D𝑬 ᴍ𝑬 ᴀ𝑬ℛᴏ𝐏Lᴀɴ𝑬𝐏ᴀℛK KᴀℛK𝑬 UDᴀᴀɴ BHᴀℛ DUGᴀ ✈️🛫",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 🇸 UTLI BᴏᴍB FᴏD DUɴGᴀ T𝑬ℛI ᴍᴀᴀ KI JHᴀᴀT𝑬 JᴀL K𝑬 KHᴀᴀK Hᴏ JᴀY𝑬GI💣",
    "T𝑬ℛI ᴍᴀᴀKI CHUT ᴍ𝑬 🇸 CᴏᴏT𝑬ℛ DᴀᴀL DUGᴀ👅",
    "T𝑬ℛ𝑬 B𝑬H𝑬ɴ K CHUT ᴍ𝑬 CHᴀKU DᴀᴀL Kᴀℛ CHUT Kᴀ KHᴏᴏɴ Kᴀℛ DUGᴀ",
    "T𝑬ℛ𝑬 B𝑬H𝑬ɴ K CHUT ᴍ𝑬 CHᴀKU DᴀᴀL Kᴀℛ CHUT Kᴀ KHᴏᴏɴ Kᴀℛ DUGᴀ",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT KᴀKT𝑬 🤱 GᴀLI K𝑬 KUTTᴏ 🦮 ᴍ𝑬 BᴀᴀT DUɴGᴀ 𝐏HIℛ 🍞 Bℛ𝑬ᴀD KI TᴀℛH KHᴀY𝑬ɴG𝑬 Wᴏ T𝑬ℛI ᴍᴀᴀ KI CHUT",
    "DUDH HILᴀᴀUɴGᴀ T𝑬ℛI VᴀH𝑬𝑬ɴ K𝑬 U𝐏ℛ ɴICH𝑬 🆙🆒😙",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 ✋ HᴀTTH DᴀLK𝑬 👶 BᴀCCH𝑬 ɴIKᴀL DUɴGᴀ 😍",
    "T𝑬ℛI B𝑬Hɴ KI CHUT ᴍ𝑬 K𝑬L𝑬 K𝑬 CHILK𝑬 🍌🍌😍",
    "T𝑬ℛI BH𝑬ɴ KI CHUT ᴍ𝑬 U🇸 𝑬ℛBᴏT LᴀGᴀᴀUɴGᴀ 🇸 ᴀ🇸 T𝑬 🇸 𝐏ᴀᴍ K𝑬 CHᴏD𝑬",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ DHᴀɴDH𝑬 VᴀᴀLI 😋😛",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬 ᴀC LᴀGᴀ DUɴGᴀ 🇸 ᴀᴀℛI GᴀℛᴍI ɴIKᴀL JᴀᴀY𝑬GI",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ Kᴏ HᴏℛLICK🇸  𝐏𝑬𝑬LᴀUɴGᴀ ᴍᴀDᴀℛCHᴏD😚",
    "T𝑬ℛI ᴍᴀᴀ KI GᴀᴀɴD ᴍ𝑬 🇸 ᴀℛIYᴀ DᴀᴀL DUɴGᴀ ᴍᴀDᴀℛCHᴏD U🇸 I 🇸 ᴀℛIY𝑬 𝐏ℛ TᴀɴG K𝑬 BᴀCH𝑬 𝐏ᴀIDᴀ HᴏɴG𝑬 😱😱",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ KᴏLKᴀTᴀ VᴀᴀL𝑬 JITU BHᴀIYᴀ Kᴀ LUɴD ᴍUBᴀℛᴀK 🤩🤩",
    "T𝑬ℛI ᴍUᴍᴍY KI FᴀɴTᴀ🇸 Y HU LᴀWD𝑬, TU ᴀ𝐏ɴI BH𝑬ɴ Kᴏ 🇸 ᴍBHᴀᴀL 😈😈",
    "T𝑬ℛᴀ 𝐏𝑬HLᴀ Bᴀᴀ𝐏 HU ᴍᴀDᴀℛCHᴏD ",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬 XVID𝑬ᴏ🇸 .Cᴏᴍ CHᴀLᴀ K𝑬 ᴍUTH ᴍᴀᴀℛUɴGᴀ 🤡😹",
    "T𝑬ℛI ᴍᴀᴀ Kᴀ GℛᴏU𝐏 VᴀᴀLᴏɴ 🇸 ᴀᴀTH ᴍILK𝑬 GᴀɴG BᴀɴG KℛUɴGᴀ🙌🏻☠️ ",
    "T𝑬ℛI IT𝑬ᴍ KI GᴀᴀɴD ᴍ𝑬 LUɴD DᴀᴀLK𝑬,T𝑬ℛ𝑬 JᴀI🇸 ᴀ 𝑬K ᴏℛ ɴIKᴀᴀL DUɴGᴀ ᴍᴀDᴀℛCHᴏD🤘🏻🙌🏻☠️ ",
    "ᴀUKᴀᴀT ᴍ𝑬 ℛ𝑬H Vℛɴᴀ GᴀᴀɴD ᴍ𝑬 DᴀɴDᴀ DᴀᴀL K𝑬 ᴍUH 🇸 𝑬 ɴIKᴀᴀL DUɴGᴀ 🇸 HᴀℛIℛ BHI DᴀɴD𝑬 J𝑬🇸 ᴀ DIKH𝑬Gᴀ 🙄🤭🤭",
    "T𝑬ℛI ᴍUᴍᴍY K𝑬 🇸 ᴀᴀTH LUDᴏ KH𝑬LT𝑬 KH𝑬LT𝑬 U🇸 K𝑬 ᴍUH ᴍ𝑬 ᴀ𝐏ɴᴀ LᴏDᴀ D𝑬 DUɴGᴀ☝🏻☝🏻😬",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ Kᴏ ᴀ𝐏ɴ𝑬 LUɴD 𝐏ℛ ITɴᴀ JHULᴀᴀUɴGᴀ KI JHULT𝑬 JHULT𝑬 HI BᴀCHᴀ 𝐏ᴀIDᴀ Kℛ D𝑬GI👀👯 ",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I BᴀTT𝑬ℛY LᴀGᴀ K𝑬 𝐏ᴏW𝑬ℛBᴀɴK Bᴀɴᴀ DUɴGᴀ 🔋 🔥🤩",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I C++ 🇸 TℛIɴG 𝑬ɴCℛY𝐏TIᴏɴ LᴀGᴀ DUɴGᴀ BᴀHTI HUYI CHUT ℛUK JᴀY𝑬GIIII😈🔥😍",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 GᴀᴀɴD ᴍ𝑬I JHᴀᴀDU DᴀL K𝑬 ᴍᴏℛ 🦚 Bᴀɴᴀ DUɴGᴀᴀ 🤩🥵😱",
    "T𝑬ℛI CHUT KI CHUT ᴍ𝑬I 🇸 HᴏULD𝑬ℛIɴG Kᴀℛ DUɴGᴀᴀ HILᴀT𝑬 HUY𝑬 BHI DᴀℛD HᴏGᴀᴀᴀ😱🤮👺",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ ℛ𝑬DI 𝐏𝑬 BᴀITHᴀL K𝑬 U🇸 🇸 𝑬 U🇸 KI CHUT BILWᴀUɴGᴀᴀ 💰 😵🤩",
    "BHᴏ🇸 DIK𝑬 T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I 4 HᴏL𝑬 HᴀI Uɴᴍ𝑬 ᴍ🇸 𝑬ᴀL LᴀGᴀ BᴀHUT BᴀH𝑬TI HᴀI BHᴏFDIK𝑬👊🤮🤢🤢",
    "T𝑬ℛI BᴀH𝑬ɴ KI CHUT ᴍ𝑬I BᴀℛGᴀD Kᴀ 𝐏𝑬D UGᴀ DUɴGᴀᴀ Cᴏℛᴏɴᴀ ᴍ𝑬I 🇸 ᴀB ᴏXYG𝑬ɴ L𝑬Kᴀℛ JᴀY𝑬ɴG𝑬🤢🤩🥳",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I 🇸 UDᴏ LᴀGᴀ K𝑬 BIG🇸 𝐏ᴀᴍ LᴀGᴀ K𝑬 9999 FUCK LᴀGᴀᴀ DU 🤩🥳🔥",
    "T𝑬ℛI VᴀH𝑬ɴ K𝑬 BHᴏ🇸 DIK𝑬 ᴍ𝑬I B𝑬🇸 ᴀɴ K𝑬 LᴀDDU BHᴀℛ DUɴGᴀ🤩🥳🔥😈",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT KHᴏD K𝑬 U🇸 ᴍ𝑬 CYLIɴD𝑬ℛ ⛽️ FIT KᴀℛK𝑬 U🇸 ᴍ𝑬𝑬 DᴀL ᴍᴀKHᴀɴI BᴀɴᴀUɴGᴀᴀᴀ🤩👊🔥",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I 🇸 H𝑬𝑬🇸 Hᴀ DᴀL DUɴGᴀᴀᴀ ᴀUℛ CHᴀUℛᴀH𝑬 𝐏𝑬 TᴀᴀɴG DUɴGᴀ BHᴏ🇸 DIK𝑬😈😱🤩",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I Cℛ𝑬DIT CᴀℛD DᴀL K𝑬 ᴀG𝑬 🇸 𝑬 500 K𝑬 Kᴀᴀℛ𝑬 Kᴀᴀℛ𝑬 ɴᴏT𝑬 ɴIKᴀLUɴGᴀᴀ BHᴏ🇸 DIK𝑬💰💰🤩",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 🇸 ᴀTH 🇸 Uᴀℛ Kᴀ 🇸 𝑬X KᴀℛWᴀ DUɴGᴀᴀ 𝑬K 🇸 ᴀTH 6-6 BᴀCH𝑬 D𝑬GI💰🔥😱",
    "T𝑬ℛI BᴀH𝑬ɴ KI CHUT ᴍ𝑬I ᴀ𝐏𝐏L𝑬 Kᴀ 18W WᴀLᴀ CHᴀℛG𝑬ℛ 🔥🤩",
    "T𝑬ℛI BᴀH𝑬ɴ KI GᴀᴀɴD ᴍ𝑬I ᴏɴ𝑬𝐏LU🇸  Kᴀ Wℛᴀ𝐏 CHᴀℛG𝑬ℛ 30W HIGH 𝐏ᴏW𝑬ℛ 💥😂😎",
    "T𝑬ℛI BᴀH𝑬ɴ KI CHUT Kᴏ ᴀᴍᴀᴢᴏᴏɴ 🇸 𝑬 ᴏℛD𝑬ℛ KᴀℛUɴGᴀ 10 ℛ🇸  ᴍ𝑬I ᴀUℛ FLI𝐏KᴀℛT 𝐏𝑬 20 ℛ🇸  ᴍ𝑬I B𝑬CH DUɴGᴀ🤮👿😈🤖",
    "T𝑬ℛI ᴍᴀᴀ KI BᴀDI BHUɴD ᴍ𝑬 ᴏᴏᴍᴀTᴏ DᴀL K𝑬 🇸 UBWᴀY Kᴀ BFF V𝑬G 🇸 UB CᴏᴍBᴏ [15cᴍ , 16 iɴch𝑬🇸  ] ᴏℛD𝑬ℛ CᴏD KℛVᴀUɴGᴀ ᴏℛ T𝑬ℛI ᴍᴀᴀ JᴀB DILIV𝑬ℛY D𝑬ɴ𝑬 ᴀY𝑬GI TᴀB U🇸 𝐏𝑬 JᴀᴀDU KℛUɴGᴀ ᴏℛ FIℛ 9 ᴍᴏɴTH BᴀᴀD Vᴏ 𝑬K ᴏℛ Fℛ𝑬𝑬 DILIV𝑬ℛY D𝑬GI🙀👍🥳🔥",
    "T𝑬ℛI BH𝑬ɴ KI CHUT KᴀᴀLI🙁🤣💥",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 CHᴀɴG𝑬🇸  CᴏᴍᴍIT KℛUGᴀ FIℛ T𝑬ℛI BH𝑬𝑬ɴ KI CHUT ᴀUTᴏᴍᴀTICᴀLLY U𝐏DᴀT𝑬 HᴏJᴀᴀY𝑬GI🤖🙏🤔",
    "T𝑬ℛI ᴍᴀU🇸 I K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬I IɴDIᴀɴ ℛᴀILWᴀY 🚂💥😂",
    "TU T𝑬ℛI BᴀH𝑬ɴ T𝑬ℛᴀ KHᴀɴDᴀɴ 🇸 ᴀB BᴀH𝑬ɴ K𝑬 LᴀWD𝑬 ℛᴀɴDI HᴀI ℛᴀɴDI 🤢✅🔥",
    "T𝑬ℛI BᴀH𝑬ɴ KI CHUT ᴍ𝑬I IᴏɴIC BᴏɴD Bᴀɴᴀ K𝑬 VIℛGIɴITY Lᴏᴏ🇸 𝑬 KᴀℛWᴀ DUɴGᴀ U🇸 KI 📚 😎🤩",
    "T𝑬ℛI ℛᴀɴDI ᴍᴀᴀ 🇸 𝑬 𝐏UCHɴᴀ Bᴀᴀ𝐏 Kᴀ ɴᴀᴀᴍ BᴀH𝑬ɴ K𝑬 LᴏD𝑬𝑬𝑬𝑬𝑬 🤩🥳😳",
    "TU ᴀUℛ T𝑬ℛI ᴍᴀᴀ Dᴏɴᴏ KI BHᴏ🇸 D𝑬 ᴍ𝑬I ᴍ𝑬Tℛᴏ CHᴀLWᴀ DUɴGᴀ ᴍᴀDᴀℛXHᴏD 🚇🤩😱🥶",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ ITɴᴀ CHᴏDUɴGᴀ T𝑬ℛᴀ Bᴀᴀ𝐏 BHI U🇸 Kᴏ 𝐏ᴀHCHᴀɴᴀɴ𝑬 🇸 𝑬 ᴍᴀɴᴀ Kᴀℛ D𝑬Gᴀ😂👿🤩",
    "T𝑬ℛI BᴀH𝑬ɴ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬I HᴀIℛ DℛY𝑬ℛ CHᴀLᴀ DUɴGᴀᴀ💥🔥🔥",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬I T𝑬L𝑬Gℛᴀᴍ KI 🇸 ᴀℛI ℛᴀɴDIYᴏɴ Kᴀ ℛᴀɴDI KHᴀɴᴀ KHᴏL DUɴGᴀᴀ👿🤮😎",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴀL𝑬Xᴀ DᴀL K𝑬𝑬 DJ BᴀJᴀUɴGᴀᴀᴀ 🎶 ⬆️🤩💥",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬I GITHUB DᴀL K𝑬 ᴀ𝐏ɴᴀ BᴏT Hᴏ🇸 T KᴀℛUɴGᴀᴀ 🤩👊👤😍",
    "T𝑬ℛI BᴀH𝑬ɴ Kᴀ V𝐏🇸  Bᴀɴᴀ K𝑬 24*7 Bᴀ🇸 H CHUDᴀI CᴏᴍᴍᴀɴD D𝑬 DUɴGᴀᴀ 🤩💥🔥🔥",
    "T𝑬ℛI ᴍUᴍᴍY KI CHUT ᴍ𝑬I T𝑬ℛ𝑬 LᴀɴD Kᴏ DᴀL K𝑬 KᴀᴀT DUɴGᴀ ᴍᴀDᴀℛCHᴏD 🔪😂🔥",
    "🇸 Uɴ T𝑬ℛI ᴍᴀᴀ Kᴀ BHᴏ🇸 Dᴀ ᴀUℛ T𝑬ℛI BᴀH𝑬ɴ Kᴀ BHI BHᴏ🇸 Dᴀ 👿😎👊",
    "TUJH𝑬 D𝑬KH K𝑬 T𝑬ℛI ℛᴀɴDI BᴀH𝑬ɴ 𝐏𝑬 Tᴀℛᴀ🇸  ᴀTᴀ HᴀI ᴍUJH𝑬 BᴀH𝑬ɴ K𝑬 LᴏD𝑬𝑬𝑬𝑬 👿💥🤩🔥",
    "🇸 Uɴ ᴍᴀDᴀℛCHᴏD JYᴀDᴀ ɴᴀ UCHᴀL ᴍᴀᴀ CHᴏD D𝑬ɴG𝑬 𝑬K ᴍIɴ ᴍ𝑬I ✅🤣🔥🤩",
    "ᴀ𝐏ɴI ᴀᴍᴍᴀ 🇸 𝑬 𝐏UCHɴᴀ U🇸 Kᴏ U🇸  KᴀᴀLI ℛᴀᴀT ᴍ𝑬I KᴀUɴ CHᴏDɴ𝑬𝑬 ᴀYᴀ THᴀᴀᴀ! T𝑬ℛ𝑬 I🇸  𝐏ᴀ𝐏ᴀ Kᴀ ɴᴀᴀᴍ L𝑬GI 😂👿😳",
    "TᴏHᴀℛ BᴀHIɴ CHᴏDU BBᴀH𝑬ɴ K𝑬 LᴀWD𝑬 U🇸 ᴍ𝑬 ᴍITTI DᴀL K𝑬 C𝑬ᴍ𝑬ɴT 🇸 𝑬 BHᴀℛ DU 🏠🤢🤩💥",
    "TUJH𝑬 ᴀB TᴀK ɴᴀHI 🇸 ᴍJH ᴀYᴀ KI ᴍᴀI HI HU TUJH𝑬 𝐏ᴀIDᴀ Kᴀℛɴ𝑬 WᴀLᴀ BHᴏ🇸 DIK𝑬𝑬 ᴀ𝐏ɴI ᴍᴀᴀ 🇸 𝑬 𝐏UCH ℛᴀɴDI K𝑬 BᴀCH𝑬𝑬𝑬𝑬 🤩👊👤😍",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬I 🇸 𝐏ᴏTIFY DᴀL K𝑬 LᴏFI BᴀJᴀUɴGᴀ DIɴ BHᴀℛ 😍🎶🎶💥",
    "T𝑬ℛI ᴍᴀᴀ Kᴀ ɴᴀYᴀ ℛᴀɴDI KHᴀɴᴀ KHᴏLUɴGᴀ CHIɴTᴀ ᴍᴀT Kᴀℛ 👊🤣🤣😳",
    "T𝑬ℛᴀ Bᴀᴀ𝐏 HU BHᴏ🇸 DIK𝑬 T𝑬ℛI ᴍᴀᴀ Kᴏ ℛᴀɴDI KHᴀɴ𝑬 𝐏𝑬 CHUDWᴀ K𝑬 U🇸  𝐏ᴀI🇸 𝑬 KI DᴀᴀℛU 𝐏𝑬𝑬Tᴀ HU 🍷🤩🔥",
    "T𝑬ℛI BᴀH𝑬ɴ KI CHUT ᴍ𝑬I ᴀ𝐏ɴᴀ BᴀDᴀ 🇸 ᴀ LᴏDᴀ GHU🇸 🇸 ᴀ DUɴGᴀᴀ KᴀLLᴀᴀ𝐏 K𝑬 ᴍᴀℛ JᴀY𝑬GI 🤩😳😳🔥",
    "TᴏHᴀℛ ᴍUᴍᴍY KI CHUT ᴍ𝑬I 𝐏UℛI KI 𝐏UℛI KIɴGFI🇸 H𝑬ℛ KI BᴏTTL𝑬 DᴀL K𝑬 TᴏD DUɴGᴀ ᴀɴD𝑬ℛ HI 😱😂🤩",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ ITɴᴀ CHᴏDUɴGᴀ KI 🇸 ᴀ𝐏ɴ𝑬 ᴍ𝑬I BHI ᴍ𝑬ℛI CHUDᴀI YᴀᴀD Kᴀℛ𝑬GI ℛᴀɴDI 🥳😍👊💥",
    "T𝑬ℛI ᴍUᴍᴍY ᴀUℛ BᴀH𝑬ɴ Kᴏ DᴀUDᴀ DᴀUDᴀ ɴ𝑬 CHᴏDUɴGᴀ UɴK𝑬 ɴᴏ BᴏLɴ𝑬 𝐏𝑬 BHI LᴀɴD GHU🇸 ᴀ DUɴGᴀ ᴀɴD𝑬ℛ TᴀK 😎😎🤣🔥",
    "T𝑬ℛI ᴍUᴍᴍY KI CHUT Kᴏ ᴏɴLIɴ𝑬 ᴏLX 𝐏𝑬 B𝑬CHUɴGᴀ ᴀUℛ 𝐏ᴀI🇸 𝑬 🇸 𝑬 T𝑬ℛI BᴀH𝑬ɴ Kᴀ KᴏTHᴀ KHᴏL DUɴGᴀ 😎🤩😝😍",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 BHᴏ🇸 Dᴀ ITɴᴀ CHᴏDUɴGᴀ KI TU CᴀH K𝑬 BHI Wᴏ ᴍᴀ🇸 T CHUDᴀI 🇸 𝑬 DUℛ ɴHI Jᴀ 𝐏ᴀY𝑬Gᴀᴀ 😏😏🤩😍",
    "🇸 Uɴ B𝑬 ℛᴀɴDI KI ᴀULᴀᴀD TU ᴀ𝐏ɴI BᴀH𝑬ɴ 🇸 𝑬 🇸 𝑬𝑬KH KUCH KᴀI🇸 𝑬 GᴀᴀɴD ᴍᴀℛWᴀT𝑬 HᴀI😏🤬🔥💥",
    "T𝑬ℛI ᴍᴀᴀ Kᴀ Yᴀᴀℛ HU ᴍ𝑬I ᴀUℛ T𝑬ℛI BᴀH𝑬ɴ Kᴀ 𝐏Yᴀᴀℛ HU ᴍ𝑬I ᴀJᴀ ᴍ𝑬ℛᴀ LᴀɴD CHᴏᴏ🇸  L𝑬 🤩🤣💥",
    "T𝑬ℛI BH𝑬ɴ KI CHUT ᴍ𝑬 U🇸 𝑬ℛBᴏT LᴀGᴀᴀUɴGᴀ 🇸 ᴀ🇸 T𝑬 🇸 𝐏ᴀᴍ K𝑬 CHᴏD𝑬",
    "T𝑬ℛI ᴍᴀᴀ KI GᴀᴀɴD ᴍ𝑬 🇸 ᴀℛIYᴀ DᴀᴀL DUɴGᴀ ᴍᴀDᴀℛCHᴏD U🇸 I 🇸 ᴀℛIY𝑬 𝐏ℛ TᴀɴG K𝑬 BᴀCH𝑬 𝐏ᴀIDᴀ HᴏɴG𝑬 😱😱",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 ✋ HᴀTTH DᴀLK𝑬 👶 BᴀCCH𝑬 ɴIKᴀL DUɴGᴀ 😍",
    "T𝑬ℛI B𝑬Hɴ KI CHUT ᴍ𝑬 K𝑬L𝑬 K𝑬 CHILK𝑬 🤤🤤",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 🇸 UTLI BᴏᴍB FᴏD DUɴGᴀ T𝑬ℛI ᴍᴀᴀ KI JHᴀᴀT𝑬 JᴀL K𝑬 KHᴀᴀK Hᴏ JᴀY𝑬GI💣💋",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ Kᴏ HᴏℛLICK🇸  𝐏𝑬𝑬LᴀK𝑬 CHᴏDUɴGᴀ ᴍᴀDᴀℛCHᴏD😚",
    "T𝑬ℛI IT𝑬ᴍ KI GᴀᴀɴD ᴍ𝑬 LUɴD DᴀᴀLK𝑬,T𝑬ℛ𝑬 JᴀI🇸 ᴀ 𝑬K ᴏℛ ɴIKᴀᴀL DUɴGᴀ ᴍᴀDᴀℛCHᴏD😆🤤💋",
    "T𝑬ℛI VᴀH𝑬𝑬ɴ Kᴏ ᴀ𝐏ɴ𝑬 LUɴD 𝐏ℛ ITɴᴀ JHULᴀᴀUɴGᴀ KI JHULT𝑬 JHULT𝑬 HI BᴀCHᴀ 𝐏ᴀIDᴀ Kℛ D𝑬GI 💦💋",
    "🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 T𝑬ℛI ᴍᴀᴀKᴏ 🇸 ᴀDᴀK 𝐏ℛ LITᴀK𝑬 CHᴏD DUɴGᴀ 😂😆🤤",
    "ᴀB𝑬 T𝑬ℛI ᴍᴀᴀKᴀ BHᴏ🇸 Dᴀ ᴍᴀD𝑬ℛCHᴏᴏD Kℛ 𝐏ILL𝑬 𝐏ᴀ𝐏ᴀ 🇸 𝑬 LᴀD𝑬Gᴀ TU 😼😂🤤",
    "GᴀLI GᴀLI ɴ𝑬 🇸 Hᴏℛ H𝑬 T𝑬ℛI ᴍᴀᴀ ℛᴀɴDI CHᴏℛ H𝑬 💋💋💦",
    "ᴀB𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏDU ℛᴀɴDIK𝑬 𝐏ILL𝑬 KUTT𝑬 K𝑬 CHᴏD𝑬 😂👻🔥",
    "T𝑬ℛI ᴍᴀᴀKᴏ ᴀI🇸 𝑬 CHᴏDᴀ ᴀI🇸 𝑬 CHᴏDᴀ T𝑬ℛI ᴍᴀᴀᴀ B𝑬D 𝐏𝑬HI ᴍUTH DIᴀ 💦💦💦💦",
    "T𝑬ℛI B𝑬H𝑬ɴ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬 ᴀᴀᴀG LᴀGᴀDIᴀ ᴍ𝑬ℛᴀ ᴍᴏTᴀ LUɴD DᴀLK𝑬 🔥🔥💦😆😆",
    "ℛᴀɴDIK𝑬 BᴀCHH𝑬 T𝑬ℛI ᴍᴀᴀKᴏ CHᴏDU CHᴀL ɴIKᴀL",
    "KITɴᴀ CHᴏDU T𝑬ℛI ℛᴀɴDI ᴍᴀᴀKI CHUTH ᴀBB ᴀ𝐏ɴI B𝑬H𝑬ɴ Kᴏ BH𝑬J 😆👻🤤",
    "T𝑬ℛI B𝑬H𝑬ɴ KᴏTᴏ CHᴏD CHᴏDK𝑬 𝐏Uℛᴀ FᴀᴀD DIᴀ CHUTH ᴀBB T𝑬ℛI GF Kᴏ BH𝑬J 😆💦🤤",
    "T𝑬ℛI GF Kᴏ 𝑬Tɴᴀ CHᴏDᴀ B𝑬H𝑬ɴ K𝑬 LᴏD𝑬 T𝑬ℛI GF Tᴏ ᴍ𝑬ℛI ℛᴀɴDI BᴀɴGᴀYI ᴀBB CHᴀL T𝑬ℛI ᴍᴀᴀKᴏ CHᴏDTᴀ FIℛ🇸 𝑬 ♥️💦😆😆😆😆",
    "HᴀℛI HᴀℛI GHᴀᴀ🇸  ᴍ𝑬 JHᴏ𝐏Dᴀ T𝑬ℛI ᴍᴀᴀKᴀ BHᴏ🇸 Dᴀ 🤣🤣💋💦",
    "CHᴀL T𝑬ℛ𝑬 Bᴀᴀ𝐏 Kᴏ BH𝑬J T𝑬ℛᴀ Bᴀ🇸 Kᴀ ɴHI H𝑬 𝐏ᴀ𝐏ᴀ 🇸 𝑬 LᴀD𝑬Gᴀ TU",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 BᴏᴍB DᴀLK𝑬 UDᴀ DUɴGᴀ ᴍᴀᴀK𝑬 LᴀWD𝑬",
    "T𝑬ℛI ᴍᴀᴀKᴏ TℛᴀIɴ ᴍ𝑬 L𝑬JᴀK𝑬 Tᴏ𝐏 B𝑬D 𝐏𝑬 LITᴀK𝑬 CHᴏD DUɴGᴀ 🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 🤣🤣💋💋",
    "T𝑬ℛI ᴍᴀᴀᴀK𝑬 ɴUD𝑬🇸  GᴏᴏGL𝑬 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ B𝑬H𝑬ɴ K𝑬 Lᴀ𝑬WD𝑬 👻🔥",
    "T𝑬ℛI ᴍᴀᴀᴀK𝑬 ɴUD𝑬🇸  GᴏᴏGL𝑬 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ B𝑬H𝑬ɴ K𝑬 Lᴀ𝑬WD𝑬 👻🔥",
    "T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏD CHᴏDK𝑬 VID𝑬ᴏ BᴀɴᴀK𝑬 XɴXX.Cᴏᴍ 𝐏𝑬 ɴ𝑬𝑬Lᴀᴍ KᴀℛDUɴGᴀ KUTT𝑬 K𝑬 𝐏ILL𝑬 💦💋",
    "T𝑬ℛI ᴍᴀᴀᴀKI CHUDᴀI Kᴏ 𝐏ᴏℛɴHUB.Cᴏᴍ 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ 🇸 Uᴀℛ K𝑬 CHᴏD𝑬 🤣💋💦",
    "ᴀB𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏDU ℛᴀɴDIK𝑬 BᴀCHH𝑬 T𝑬ℛ𝑬Kᴏ CHᴀKKᴏ 🇸 𝑬 𝐏ILWᴀVUɴGᴀ ℛᴀɴDIK𝑬 BᴀCHH𝑬 🤣🤣",
    "T𝑬ℛI ᴍᴀᴀKI CHUTH FᴀᴀDK𝑬 ℛᴀKDIᴀ ᴍᴀᴀK𝑬 LᴏD𝑬 Jᴀᴀ ᴀBB 🇸 ILWᴀL𝑬 👄👄",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍ𝑬ℛᴀ LUɴD KᴀᴀLᴀ",
    "T𝑬ℛI B𝑬H𝑬ɴ L𝑬TI ᴍ𝑬ℛI LUɴD BᴀD𝑬 ᴍᴀ🇸 TI 🇸 𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ ᴍ𝑬ɴ𝑬 CHᴏD DᴀLᴀ BᴏHᴏT 🇸 ᴀ🇸 T𝑬 🇸 𝑬",
    "B𝑬T𝑬 TU Bᴀᴀ𝐏 🇸 𝑬 L𝑬Gᴀ 𝐏ᴀɴGᴀ T𝑬ℛI ᴍᴀᴀᴀ Kᴏ CHᴏD DUɴGᴀ KᴀℛK𝑬 ɴᴀɴGᴀ 💦💋",
    "HᴀHᴀHᴀH ᴍ𝑬ℛ𝑬 B𝑬T𝑬 ᴀGLI Bᴀᴀℛ ᴀ𝐏ɴI ᴍᴀᴀKᴏ L𝑬K𝑬 ᴀᴀYᴀ ᴍᴀTH KᴀT ᴏℛ ᴍ𝑬ℛ𝑬 ᴍᴏT𝑬 LUɴD 🇸 𝑬 CHUDWᴀYᴀ ᴍᴀTH Kᴀℛ",
    "CHᴀL B𝑬Tᴀ TUJH𝑬 ᴍᴀᴀF KIᴀ 🤣 ᴀBB ᴀ𝐏ɴI GF Kᴏ BH𝑬J",
    "🇸 Hᴀℛᴀᴍ Kᴀℛ T𝑬ℛI B𝑬H𝑬ɴ Kᴀ BHᴏ🇸 Dᴀ KITɴᴀ GᴀᴀLIᴀ 🇸 UɴWᴀY𝑬Gᴀ ᴀ𝐏ɴI ᴍᴀᴀᴀ B𝑬H𝑬ɴ K𝑬 U𝐏𝑬ℛ",
    "ᴀB𝑬 ℛᴀɴDIK𝑬 BᴀCHH𝑬 ᴀUKᴀT ɴHI H𝑬Tᴏ ᴀ𝐏ɴI ℛᴀɴDI ᴍᴀᴀKᴏ L𝑬K𝑬 ᴀᴀYᴀ ᴍᴀTH Kᴀℛ HᴀHᴀHᴀHᴀ",
    "KIDᴏ ᴍᴀDᴀℛCHᴏD T𝑬ℛI ᴍᴀᴀKᴏ CHᴏD CHᴏDK𝑬 T𝑬ℛℛ LIY𝑬 BHᴀI D𝑬DIYᴀ",
    "JUɴGL𝑬 ᴍ𝑬 ɴᴀCHTᴀ H𝑬 ᴍᴏℛ𝑬 T𝑬ℛI ᴍᴀᴀKI CHUDᴀI D𝑬KK𝑬 🇸 ᴀB BᴏLT𝑬 ᴏɴC𝑬 ᴍᴏℛ𝑬 ᴏɴC𝑬 ᴍᴏℛ𝑬 🤣🤣💦💋",
    "GᴀLI GᴀLI ᴍ𝑬 ℛ𝑬HTᴀ H𝑬 🇸 ᴀɴD T𝑬ℛI ᴍᴀᴀKᴏ CHᴏD DᴀLᴀ ᴏℛ Bᴀɴᴀ DIᴀ ℛᴀɴD 🤤🤣",
    "🇸 ᴀB BᴏLT𝑬 ᴍUJHKᴏ 𝐏ᴀ𝐏ᴀ KYᴏUɴKI ᴍ𝑬ɴ𝑬 BᴀɴᴀDIᴀ T𝑬ℛI ᴍᴀᴀKᴏ 𝐏ℛ𝑬Gɴ𝑬ɴT 🤣🤣",
    "🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 T𝑬ℛI ᴍᴀᴀKI CHUTH ᴍ𝑬 🇸 Uᴀℛ Kᴀ LᴏUDᴀ ᴏℛ T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍ𝑬ℛᴀ LᴏDᴀ",
    "CHᴀL CHᴀL ᴀ𝐏ɴI ᴍᴀᴀKI CHUCHIYᴀ DIKᴀ",
    "HᴀHᴀHᴀHᴀ BᴀCHH𝑬 T𝑬ℛI ᴍᴀᴀᴀKᴏ CHᴏD DIᴀ ɴᴀɴGᴀ KᴀℛK𝑬",
    "T𝑬ℛI GF H𝑬 BᴀDI 🇸 𝑬XY U🇸 Kᴏ 𝐏ILᴀK𝑬 CHᴏᴏD𝑬ɴG𝑬 𝐏𝑬𝐏🇸 I",
    "2 ℛU𝐏ᴀY KI 𝐏𝑬𝐏🇸 I T𝑬ℛI ᴍUᴍᴍY 🇸 ᴀB🇸 𝑬 🇸 𝑬XY 💋💦",
    "T𝑬ℛI ᴍᴀᴀKᴏ CH𝑬𝑬ᴍ🇸  🇸 𝑬 CHUDWᴀVUɴGᴀ ᴍᴀD𝑬ℛCHᴏᴏD K𝑬 𝐏ILL𝑬 💦🤣",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍUTHK𝑬 Fᴀℛᴀℛ HᴏJᴀVUɴGᴀ HUI HUI HUI",
    "🇸 𝐏𝑬𝑬D Lᴀᴀᴀ T𝑬ℛI B𝑬H𝑬ɴ CHᴏDU ℛᴀɴDIK𝑬 𝐏ILL𝑬 💋💦🤣",
    "ᴀℛ𝑬 ℛ𝑬 ᴍ𝑬ℛ𝑬 B𝑬T𝑬 KYᴏUɴ 🇸 𝐏𝑬𝑬D 𝐏ᴀKᴀD ɴᴀ 𝐏ᴀᴀᴀ ℛᴀHᴀ ᴀ𝐏ɴ𝑬 Bᴀᴀ𝐏 Kᴀ HᴀHᴀH🤣🤣",
    "🇸 Uɴ 🇸 Uɴ 🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 JHᴀɴTᴏ K𝑬 🇸 ᴏUDᴀGᴀℛ ᴀ𝐏ɴI ᴍUᴍᴍY KI ɴUD𝑬🇸  BH𝑬J",
    "ᴀB𝑬 🇸 Uɴ LᴏD𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴀ BHᴏ🇸 Dᴀ FᴀᴀD DUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀKᴏ KHUL𝑬 BᴀJᴀℛ ᴍ𝑬 CHᴏD DᴀLᴀ 🤣🤣💋",
]


RRAID = [
    "ᴍᴀDᴀℛCHᴏD",
    "BHᴏ🇸 DIK𝑬",
    "LᴀᴀᴀW𝑬𝑬𝑬 K𝑬 BᴀᴀᴀᴀᴀL",
    "ᴍᴀᴀᴀᴀℛ KI JHᴀᴀᴀᴀT K𝑬 BBBBBᴀᴀᴀᴀᴀLLLLL",
    "ᴍᴀDℛCHᴏD..",
    "T𝑬ℛI ᴍᴀ KI CHUT..",
    "LWD𝑬 K𝑬 BᴀᴀᴀLLL.",
    "ᴍᴀCHᴀℛ KI JHᴀᴀT K𝑬 BᴀᴀᴀLLLL",
    "T𝑬ℛI ᴍᴀ KI CHUT ᴍ DU Tᴀ𝐏ᴀ Tᴀ𝐏?",
    "T𝑬ℛI ᴍᴀ Kᴀ BHᴏ🇸 Dᴀᴀ",
    "T𝑬ℛI BHɴ 🇸 B🇸 B𝑬 BDI ℛᴀɴDI.",
    "T𝑬ℛI ᴍᴀ ᴏ🇸 🇸 𝑬 BᴀDI ℛᴀɴDDDDD",
    "T𝑬ℛᴀ Bᴀᴀ𝐏 CHKᴀᴀᴀᴀ",
    "KITɴI CHᴏDU T𝑬ℛI ᴍᴀ ᴀB ᴏℛ..",
    "T𝑬ℛI ᴍᴀ CHᴏD DI Hᴍ ɴ𝑬",
    "T𝑬ℛI ᴍᴀ K𝑬 🇸 TH ℛ𝑬𝑬L🇸  Bɴ𝑬Gᴀ ℛᴏᴀD 𝐏𝑬𝑬",
    "T𝑬ℛI ᴍᴀ KI CHUT 𝑬K Dᴀᴍ Tᴏ𝐏 🇸 𝑬XY",
    "ᴍᴀLUᴍ ɴᴀ 𝐏Hℛ K𝑬🇸 𝑬 L𝑬Tᴀ HU ᴍ T𝑬ℛI ᴍᴀ KI CHUT Tᴀ𝐏ᴀ Tᴀ𝐏𝐏𝐏𝐏𝐏",
    "LUɴD K𝑬 CHᴏD𝑬 TU K𝑬ℛ𝑬Gᴀ TY𝐏Iɴ",
    "🇸 𝐏𝑬𝑬D 𝐏KD LWD𝑬𝑬𝑬𝑬",
    "Bᴀᴀ𝐏 KI 🇸 𝐏𝑬𝑬D ᴍTCH Kℛℛℛ",
    "LWD𝑬𝑬𝑬",
    "𝐏ᴀ𝐏ᴀ KI 🇸 𝐏𝑬𝑬D ᴍTCH ɴHI Hᴏ ℛHI KYᴀ",
    "ᴀL𝑬 ᴀL𝑬 ᴍ𝑬Lᴀ BCHᴀᴀᴀᴀ",
    "CHUD GYᴀ 𝐏ᴀ𝐏ᴀ 🇸 𝑬𝑬𝑬",
    "KI🇸 ᴀɴ Kᴏ KHᴏDɴᴀ ᴏℛ",
    "🇸 ᴀL𝑬 ℛᴀ𝐏𝑬KL KℛDKᴀ T𝑬ℛᴀ",
    "HᴀHᴀHᴀᴀᴀᴀᴀ",
    "KID🇸 🇸 🇸 🇸 ",
    "T𝑬ℛI ᴍᴀ CHUD GYI ᴀB Fℛᴀℛ ᴍT Hᴏɴᴀ",
    "Y𝑬 LDɴG𝑬 Bᴀ𝐏𝐏 🇸 𝑬",
    "KID🇸 🇸 🇸  Fℛᴀℛ HᴀHᴀHH",
    "BH𝑬ɴ K𝑬 LWD𝑬 🇸 Hℛᴍ Kℛ",
    "KITɴI GLIYᴀ 𝐏DW𝑬Gᴀ ᴀ𝐏ɴI ᴍᴀ Kᴏ",
    "ɴᴀLL𝑬𝑬",
    "🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 T𝑬ℛI ᴍᴀᴀKᴏ 🇸 ᴀDᴀK 𝐏ℛ LITᴀK𝑬 CHᴏD DUɴGᴀ 😂😆🤤",
    "ᴀB𝑬 T𝑬ℛI ᴍᴀᴀKᴀ BHᴏ🇸 Dᴀ ᴍᴀD𝑬ℛCHᴏᴏD Kℛ 𝐏ILL𝑬 𝐏ᴀ𝐏ᴀ 🇸 𝑬 LᴀD𝑬Gᴀ TU 😼😂🤤",
    "GᴀLI GᴀLI ɴ𝑬 🇸 Hᴏℛ H𝑬 T𝑬ℛI ᴍᴀᴀ ℛᴀɴDI CHᴏℛ H𝑬 💋💋💦",
    "ᴀB𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏDU ℛᴀɴDIK𝑬 𝐏ILL𝑬 KUTT𝑬 K𝑬 CHᴏD𝑬 😂👻🔥",
    "T𝑬ℛI ᴍᴀᴀKᴏ ᴀI🇸 𝑬 CHᴏDᴀ ᴀI🇸 𝑬 CHᴏDᴀ T𝑬ℛI ᴍᴀᴀᴀ B𝑬D 𝐏𝑬HI ᴍUTH DIᴀ 💦💦💦💦",
    "T𝑬ℛI B𝑬H𝑬ɴ K𝑬 BHᴏ🇸 D𝑬 ᴍ𝑬 ᴀᴀᴀG LᴀGᴀDIᴀ ᴍ𝑬ℛᴀ ᴍᴏTᴀ LUɴD DᴀLK𝑬 🔥🔥💦😆😆",
    "ℛᴀɴDIK𝑬 BᴀCHH𝑬 T𝑬ℛI ᴍᴀᴀKᴏ CHᴏDU CHᴀL ɴIKᴀL",
    "KITɴᴀ CHᴏDU T𝑬ℛI ℛᴀɴDI ᴍᴀᴀKI CHUTH ᴀBB ᴀ𝐏ɴI B𝑬H𝑬ɴ Kᴏ BH𝑬J 😆👻🤤",
    "T𝑬ℛI B𝑬H𝑬ɴ KᴏTᴏ CHᴏD CHᴏDK𝑬 𝐏Uℛᴀ FᴀᴀD DIᴀ CHUTH ᴀBB T𝑬ℛI GF Kᴏ BH𝑬J 😆💦🤤",
    "T𝑬ℛI GF Kᴏ 𝑬Tɴᴀ CHᴏDᴀ B𝑬H𝑬ɴ K𝑬 LᴏD𝑬 T𝑬ℛI GF Tᴏ ᴍ𝑬ℛI ℛᴀɴDI BᴀɴGᴀYI ᴀBB CHᴀL T𝑬ℛI ᴍᴀᴀKᴏ CHᴏDTᴀ FIℛ🇸 𝑬 ♥️💦😆😆😆😆",
    "HᴀℛI HᴀℛI GHᴀᴀ🇸  ᴍ𝑬 JHᴏ𝐏Dᴀ T𝑬ℛI ᴍᴀᴀKᴀ BHᴏ🇸 Dᴀ 🤣🤣💋💦",
    "CHᴀL T𝑬ℛ𝑬 Bᴀᴀ𝐏 Kᴏ BH𝑬J T𝑬ℛᴀ Bᴀ🇸 Kᴀ ɴHI H𝑬 𝐏ᴀ𝐏ᴀ 🇸 𝑬 LᴀD𝑬Gᴀ TU",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 BᴏᴍB DᴀLK𝑬 UDᴀ DUɴGᴀ ᴍᴀᴀK𝑬 LᴀWD𝑬",
    "T𝑬ℛI ᴍᴀᴀKᴏ TℛᴀIɴ ᴍ𝑬 L𝑬JᴀK𝑬 Tᴏ𝐏 B𝑬D 𝐏𝑬 LITᴀK𝑬 CHᴏD DUɴGᴀ 🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 🤣🤣💋💋",
    "T𝑬ℛI ᴍᴀᴀᴀK𝑬 ɴUD𝑬🇸  GᴏᴏGL𝑬 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ B𝑬H𝑬ɴ K𝑬 Lᴀ𝑬WD𝑬 👻🔥",
    "T𝑬ℛI ᴍᴀᴀᴀK𝑬 ɴUD𝑬🇸  GᴏᴏGL𝑬 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ B𝑬H𝑬ɴ K𝑬 Lᴀ𝑬WD𝑬 👻🔥",
    "T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏD CHᴏDK𝑬 VID𝑬ᴏ BᴀɴᴀK𝑬 XɴXX.Cᴏᴍ 𝐏𝑬 ɴ𝑬𝑬Lᴀᴍ KᴀℛDUɴGᴀ KUTT𝑬 K𝑬 𝐏ILL𝑬 💦💋",
    "T𝑬ℛI ᴍᴀᴀᴀKI CHUDᴀI Kᴏ 𝐏ᴏℛɴHUB.Cᴏᴍ 𝐏𝑬 U𝐏LᴏᴀD KᴀℛDUɴGᴀ 🇸 Uᴀℛ K𝑬 CHᴏD𝑬 🤣💋💦",
    "ᴀB𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ CHᴏDU ℛᴀɴDIK𝑬 BᴀCHH𝑬 T𝑬ℛ𝑬Kᴏ CHᴀKKᴏ 🇸 𝑬 𝐏ILWᴀVUɴGᴀ ℛᴀɴDIK𝑬 BᴀCHH𝑬 🤣🤣",
    "T𝑬ℛI ᴍᴀᴀKI CHUTH FᴀᴀDK𝑬 ℛᴀKDIᴀ ᴍᴀᴀK𝑬 LᴏD𝑬 Jᴀᴀ ᴀBB 🇸 ILWᴀL𝑬 👄👄",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍ𝑬ℛᴀ LUɴD KᴀᴀLᴀ",
    "T𝑬ℛI B𝑬H𝑬ɴ L𝑬TI ᴍ𝑬ℛI LUɴD BᴀD𝑬 ᴍᴀ🇸 TI 🇸 𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴏ ᴍ𝑬ɴ𝑬 CHᴏD DᴀLᴀ BᴏHᴏT 🇸 ᴀ🇸 T𝑬 🇸 𝑬",
    "B𝑬T𝑬 TU Bᴀᴀ𝐏 🇸 𝑬 L𝑬Gᴀ 𝐏ᴀɴGᴀ T𝑬ℛI ᴍᴀᴀᴀ Kᴏ CHᴏD DUɴGᴀ KᴀℛK𝑬 ɴᴀɴGᴀ 💦💋",
    "HᴀHᴀHᴀH ᴍ𝑬ℛ𝑬 B𝑬T𝑬 ᴀGLI Bᴀᴀℛ ᴀ𝐏ɴI ᴍᴀᴀKᴏ L𝑬K𝑬 ᴀᴀYᴀ ᴍᴀTH KᴀT ᴏℛ ᴍ𝑬ℛ𝑬 ᴍᴏT𝑬 LUɴD 🇸 𝑬 CHUDWᴀYᴀ ᴍᴀTH Kᴀℛ",
    "CHᴀL B𝑬Tᴀ TUJH𝑬 ᴍᴀᴀF KIᴀ 🤣 ᴀBB ᴀ𝐏ɴI GF Kᴏ BH𝑬J",
    "🇸 Hᴀℛᴀᴍ Kᴀℛ T𝑬ℛI B𝑬H𝑬ɴ Kᴀ BHᴏ🇸 Dᴀ KITɴᴀ GᴀᴀLIᴀ 🇸 UɴWᴀY𝑬Gᴀ ᴀ𝐏ɴI ᴍᴀᴀᴀ B𝑬H𝑬ɴ K𝑬 U𝐏𝑬ℛ",
    "ᴀB𝑬 ℛᴀɴDIK𝑬 BᴀCHH𝑬 ᴀUKᴀT ɴHI H𝑬Tᴏ ᴀ𝐏ɴI ℛᴀɴDI ᴍᴀᴀKᴏ L𝑬K𝑬 ᴀᴀYᴀ ᴍᴀTH Kᴀℛ HᴀHᴀHᴀHᴀ",
    "KIDᴏ ᴍᴀDᴀℛCHᴏD T𝑬ℛI ᴍᴀᴀKᴏ CHᴏD CHᴏDK𝑬 T𝑬ℛℛ LIY𝑬 BHᴀI D𝑬DIYᴀ",
    "JUɴGL𝑬 ᴍ𝑬 ɴᴀCHTᴀ H𝑬 ᴍᴏℛ𝑬 T𝑬ℛI ᴍᴀᴀKI CHUDᴀI D𝑬KK𝑬 🇸 ᴀB BᴏLT𝑬 ᴏɴC𝑬 ᴍᴏℛ𝑬 ᴏɴC𝑬 ᴍᴏℛ𝑬 🤣🤣💦💋",
    "GᴀLI GᴀLI ᴍ𝑬 ℛ𝑬HTᴀ H𝑬 🇸 ᴀɴD T𝑬ℛI ᴍᴀᴀKᴏ CHᴏD DᴀLᴀ ᴏℛ Bᴀɴᴀ DIᴀ ℛᴀɴD 🤤🤣",
    "🇸 ᴀB BᴏLT𝑬 ᴍUJHKᴏ 𝐏ᴀ𝐏ᴀ KYᴏUɴKI ᴍ𝑬ɴ𝑬 BᴀɴᴀDIᴀ T𝑬ℛI ᴍᴀᴀKᴏ 𝐏ℛ𝑬Gɴ𝑬ɴT 🤣🤣",
    "🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 T𝑬ℛI ᴍᴀᴀKI CHUTH ᴍ𝑬 🇸 Uᴀℛ Kᴀ LᴏUDᴀ ᴏℛ T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍ𝑬ℛᴀ LᴏDᴀ",
    "CHᴀL CHᴀL ᴀ𝐏ɴI ᴍᴀᴀKI CHUCHIYᴀ DIKᴀ",
    "HᴀHᴀHᴀHᴀ BᴀCHH𝑬 T𝑬ℛI ᴍᴀᴀᴀKᴏ CHᴏD DIᴀ ɴᴀɴGᴀ KᴀℛK𝑬",
    "T𝑬ℛI GF H𝑬 BᴀDI 🇸 𝑬XY U🇸 Kᴏ 𝐏ILᴀK𝑬 CHᴏᴏD𝑬ɴG𝑬 𝐏𝑬𝐏🇸 I",
    "2 ℛU𝐏ᴀY KI 𝐏𝑬𝐏🇸 I T𝑬ℛI ᴍUᴍᴍY 🇸 ᴀB🇸 𝑬 🇸 𝑬XY 💋💦",
    "T𝑬ℛI ᴍᴀᴀKᴏ CH𝑬𝑬ᴍ🇸  🇸 𝑬 CHUDWᴀVUɴGᴀ ᴍᴀD𝑬ℛCHᴏᴏD K𝑬 𝐏ILL𝑬 💦🤣",
    "T𝑬ℛI B𝑬H𝑬ɴ KI CHUTH ᴍ𝑬 ᴍUTHK𝑬 Fᴀℛᴀℛ HᴏJᴀVUɴGᴀ HUI HUI HUI",
    "🇸 𝐏𝑬𝑬D Lᴀᴀᴀ T𝑬ℛI B𝑬H𝑬ɴ CHᴏDU ℛᴀɴDIK𝑬 𝐏ILL𝑬 💋💦🤣",
    "ᴀℛ𝑬 ℛ𝑬 ᴍ𝑬ℛ𝑬 B𝑬T𝑬 KYᴏUɴ 🇸 𝐏𝑬𝑬D 𝐏ᴀKᴀD ɴᴀ 𝐏ᴀᴀᴀ ℛᴀHᴀ ᴀ𝐏ɴ𝑬 Bᴀᴀ𝐏 Kᴀ HᴀHᴀH🤣🤣",
    "🇸 Uɴ 🇸 Uɴ 🇸 Uᴀℛ K𝑬 𝐏ILL𝑬 JHᴀɴTᴏ K𝑬 🇸 ᴏUDᴀGᴀℛ ᴀ𝐏ɴI ᴍUᴍᴍY KI ɴUD𝑬🇸  BH𝑬J",
    "ᴀB𝑬 🇸 Uɴ LᴏD𝑬 T𝑬ℛI B𝑬H𝑬ɴ Kᴀ BHᴏ🇸 Dᴀ FᴀᴀD DUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀKᴏ KHUL𝑬 BᴀJᴀℛ ᴍ𝑬 CHᴏD DᴀLᴀ 🤣🤣💋",
    "🇸 Hℛᴍ Kℛ",
    "ᴍ𝑬ℛ𝑬 LUɴD K𝑬 BᴀᴀᴀᴀᴀLLLLL",
    "KITɴI GLIYᴀ 𝐏DWYGᴀ ᴀ𝐏ɴI ᴍᴀ BH𝑬ɴ Kᴏ",
    "ℛɴDI K𝑬 LDK𝑬𝑬𝑬𝑬𝑬𝑬𝑬𝑬𝑬",
    "KID🇸 🇸 🇸 🇸 🇸 🇸 🇸 🇸 🇸 🇸 🇸 🇸 ",
    "ᴀ𝐏ɴi gᴀᴀɴd ᴍ𝑬iɴ ᴍuthi dᴀᴀl",
    "ᴀ𝐏ɴi luɴd chᴏᴏ🇸 ",
    "ᴀ𝐏ɴi ᴍᴀ kᴏ jᴀ chᴏᴏ🇸 ",
    "Bh𝑬ɴ k𝑬 lᴀud𝑬",
    "Bh𝑬ɴ k𝑬 tᴀkk𝑬",
    "ᴀblᴀ T𝑬ℛᴀ KHᴀɴ Dᴀɴ CHᴏDɴ𝑬 KI BᴀℛIII",
    "B𝑬T𝑬 T𝑬ℛI ᴍᴀ 🇸 B🇸 𝑬 BDI ℛᴀɴD",
    "LUɴD K𝑬 BᴀᴀᴀL JHᴀT K𝑬 𝐏I🇸 🇸 🇸 UUUUUUU",
    "LUɴD 𝐏𝑬 LTKIT ᴍᴀᴀᴀLLLL KI BᴏɴD H TUUU",
    "Kᴀ🇸 H ᴏ🇸  DIɴ ᴍUTH ᴍℛK𝑬 🇸 ᴏJTᴀ ᴍ TUɴ 𝐏ᴀIDᴀ ɴᴀ HᴏTᴀᴀ",
    "GLTI KℛDI TUJW 𝐏ᴀIDᴀ KℛK𝑬",
    "🇸 𝐏𝑬𝑬D 𝐏KDDD",
    "Gᴀᴀɴd ᴍᴀiɴ LWDᴀ DᴀL L𝑬 ᴀ𝐏ɴI ᴍ𝑬ℛᴀᴀᴀ",
    "Gᴀᴀɴd ᴍ𝑬iɴ bᴀᴍbu D𝑬DUɴGᴀᴀᴀᴀᴀᴀ",
    "GᴀɴD FTI K𝑬 BᴀLKKK",
    "Gᴏt𝑬 kitɴ𝑬 bhi bᴀd𝑬 hᴏ, luɴd k𝑬 ɴich𝑬 hi ℛ𝑬ht𝑬 hᴀi",
    "Hᴀᴏᴀᴀℛ luɴd t𝑬ℛi gᴀᴀɴd ᴍᴀiɴ",
    "Jhᴀᴀɴt k𝑬 𝐏i🇸 🇸 u-",
    "T𝑬ℛI ᴍᴀ KI KᴀLI CHUT",
    "Khᴏt𝑬y ki ᴀuldᴀ",
    "Kutt𝑬 kᴀ ᴀwlᴀt",
    "Kutt𝑬 ki jᴀt",
    "Kutt𝑬 k𝑬 tᴀtt𝑬",
    "T𝑬TI ᴍᴀ KI.CHUT , t𝑬ℛI ᴍᴀ ℛɴDIIIIIIIIIIIIIIIIIIII",
    "Lᴀvd𝑬 k𝑬 bᴀl",
    "ᴍuh ᴍ𝑬i l𝑬l𝑬",
    "Luɴd K𝑬 𝐏ᴀ🇸 iɴ𝑬",
    "ᴍ𝑬ℛ𝑬 LWD𝑬 K𝑬 BᴀᴀᴀᴀᴀLLL",
    "HᴀHᴀHᴀᴀᴀᴀᴀᴀ",
    "CHUD GYᴀᴀᴀᴀᴀ",
    "ℛᴀɴdi khᴀɴ𝑬 KI ULᴀDDD",
    "🇸 ᴀdi hui gᴀᴀɴd",
    "T𝑬ℛi gᴀᴀɴd ᴍᴀiɴ kut𝑬 kᴀ luɴd",
    "T𝑬ℛi ᴍᴀᴀ kᴀ bhᴏ🇸 dᴀ",
    "T𝑬ℛi ᴍᴀᴀ ki chut",
    "T𝑬ℛ𝑬 gᴀᴀɴd ᴍ𝑬iɴ k𝑬𝑬d𝑬 𝐏ᴀdᴀy",
    "Ullu k𝑬 𝐏ᴀth𝑬",
    "🇸 Uɴɴ ᴍᴀD𝑬ℛCHᴏD",
    "T𝑬ℛI ᴍᴀᴀ Kᴀ BHᴏ🇸 Dᴀ",
    "B𝑬H𝑬ɴ K LUɴD",
    "T𝑬ℛI ᴍᴀᴀ Kᴀ CHUT KI CHTɴIIII",
    "ᴍ𝑬ℛᴀ LᴀWDᴀ L𝑬L𝑬 TU ᴀGᴀℛ CHᴀIY𝑬 TᴏH",
    "GᴀᴀɴDU",
    "CHUTIYᴀ",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT 𝐏𝑬 JCB CHᴀDHᴀᴀ DUɴGᴀ",
    "🇸 ᴀᴍJHᴀᴀ LᴀWD𝑬",
    "Yᴀ DU T𝑬ℛ𝑬 GᴀᴀɴD ᴍ𝑬 Tᴀ𝐏ᴀᴀ Tᴀ𝐏��",
    "T𝑬ℛI B𝑬H𝑬ɴ ᴍ𝑬ℛᴀ ℛᴏᴏ L𝑬TI HᴀI",
    "T𝑬ℛI GF K 🇸 ᴀᴀTH ᴍᴍ🇸  Bᴀɴᴀᴀ CHUKᴀ HU���不�不",
    "TU CHUTIYᴀ T𝑬ℛᴀ KHᴀɴDᴀᴀɴ CHUTIYᴀ",
    "ᴀUℛ KITɴᴀ BᴏLU B𝑬Y ᴍᴀɴɴ BHᴀℛ GᴀYᴀ ᴍ𝑬ℛᴀ�不",
    "T𝑬ℛIIIIII ᴍᴀᴀᴀᴀ KI CHUTTT ᴍ𝑬 ᴀBCD LIKH DUɴGᴀ ᴍᴀᴀ K𝑬 LᴏD𝑬",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ L𝑬Kᴀℛ ᴍᴀI Fᴀℛᴀℛ",
    "ℛᴀɴIDIII",
    "BᴀCH𝑬𝑬",
    "CHᴏDU",
    "ℛᴀɴDI",
    "ℛᴀɴDI K𝑬 𝐏ILL𝑬",
    "T𝑬ℛIIIII ᴍᴀᴀᴀ Kᴏ BH𝑬JJJ",
    "T𝑬ℛᴀᴀ Bᴀᴀᴀᴀ𝐏 HU",
    "t𝑬ℛi ᴍᴀᴀ KI CHUT ᴍ𝑬 HᴀᴀT DᴀᴀLLK𝑬 BHᴀᴀG JᴀᴀɴUGᴀ",
    "T𝑬ℛi ᴍᴀᴀ Kᴏ 🇸 ᴀℛᴀK 𝐏𝑬 L𝑬Tᴀᴀ DUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ GB ℛᴏᴀD 𝐏𝑬 L𝑬JᴀK𝑬 B𝑬CH DUɴGᴀ",
    "T𝑬ℛi ᴍᴀᴀ KI CHUT ᴍÉ KᴀᴀLI ᴍITCH",
    "T𝑬ℛI ᴍᴀᴀ 🇸 ᴀ🇸 TI ℛᴀɴDI HᴀI",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 KᴀBUTᴀℛ DᴀᴀL K𝑬 🇸 ᴏU𝐏 BᴀɴᴀUɴGᴀ ᴍᴀDᴀℛCHᴏD",
    "T𝑬ℛI ᴍᴀᴀᴀ ℛᴀɴDI HᴀI",
    "T𝑬ℛI ᴍᴀᴀᴀ KI CHUT ᴍ𝑬 D𝑬TᴏL DᴀᴀL DUɴGᴀ ᴍᴀDᴀℛCHᴏD",
    "T𝑬ℛI ᴍᴀᴀ Kᴀᴀᴀ BHᴏ🇸 Dᴀᴀ",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 Lᴀ𝐏Tᴏ𝐏",
    "T𝑬ℛi ᴍᴀᴀ ℛᴀɴDI HᴀI",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ BI🇸 Tᴀℛ 𝐏𝑬 L𝑬TᴀᴀK𝑬 CHᴏDUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ ᴀᴍ𝑬ℛICᴀ GHUᴍᴀᴀUɴGᴀ ᴍᴀDᴀℛCHᴏD",
    "T𝑬ℛI ᴍᴀᴀ KI CHUT ᴍ𝑬 ɴᴀᴀℛIYᴀL 𝐏Hᴏℛ DUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀ K𝑬 GᴀɴD ᴍ𝑬 D𝑬TᴏL DᴀᴀL DUɴGᴀ",
    "T𝑬ℛI ᴍᴀᴀᴀ Kᴏ HᴏℛLICK🇸  𝐏ILᴀUɴGᴀ ᴍᴀDᴀℛCHᴏD",
    "T𝑬ℛI ᴍᴀᴀ Kᴏ 🇸 ᴀℛᴀK 𝐏𝑬 L𝑬Tᴀᴀᴀ DUɴGᴀᴀᴀ",
    "T𝑬ℛI ᴍᴀᴀ Kᴀᴀ BHᴏ🇸 Dᴀ",
    "ᴍ𝑬ℛᴀᴀᴀ LUɴD 𝐏ᴀKᴀD L𝑬 ᴍᴀDᴀℛCHᴏD",
    "CHU𝐏 T𝑬ℛI ᴍᴀᴀ ᴀKᴀᴀ BHᴏ🇸 Dᴀᴀ",
    "T𝑬ℛIII ᴍᴀᴀ CHUF G𝑬YII KYᴀᴀᴀ LᴀWD𝑬𝑬𝑬",
    "T𝑬ℛIII ᴍᴀᴀ Kᴀᴀ BJ🇸 ᴏDᴀᴀᴀ",
    "ᴍᴀDᴀℛXHᴏDDD",
    "T𝑬ℛIUUI ᴍᴀᴀᴀ Kᴀᴀ BH🇸 ᴏDᴀᴀᴀ",
    "T𝑬ℛIIIIII B𝑬H𝑬ɴɴɴɴ Kᴏ CHᴏDDDUUUU ᴍᴀDᴀℛXHᴏDDDD",
    "ɴIKᴀL ᴍᴀDᴀℛCHᴏD",
    "ℛᴀɴDI K𝑬 BᴀCH𝑬",
    "T𝑬ℛᴀ ᴍᴀᴀ ᴍ𝑬ℛI Fᴀɴ",
    "T𝑬ℛI 🇸 𝑬XY BᴀH𝑬ɴ KI CHUT ᴏ𝐏",
]
